### ISSUE TITLE
java.util.NoSuchElementException exception due to missing content in toTreeWithUnion.js

### ISSUE THREAD

**Issue by ramukima** [Netflix/falcor-path-utils#3]
Empty content in https://github.com/Netflix/falcor-path-utils/blob/master/lib/toTreeWithUnion.js is causing the following -

java.util.NoSuchElementException
    at java.util.Scanner.throwFor(Scanner.java:862)
    at java.util.Scanner.next(Scanner.java:1371)
    at java.util.Scanner.next(Scanner.java:304)
    at jdk.nashorn.internal.scripts.Script$Recompilation$19$8888AA$^eval_.L:33$readFile(null:308)
    at jdk.nashorn.internal.scripts.Script$Recompilation$14$2235AAAAA$^eval_.L:33$_load(null:75)
    at jdk.nashorn.internal.scripts.Script$Recompilation$4$4376AAAA$^eval\_.L:33$doRequire(null:155)
    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:648)
    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
    at jdk.nashorn.internal.runtime.ScriptFunction.invokeSync(ScriptFunction.java:1005)
    at jdk.nashorn.internal.scripts.Script$Recompilation$3$4049AAA$^eval_.L:33$Require(null:120)
    at jdk.nashorn.internal.scripts.Script$Recompilation$18$2109A$^eval_.L:33$Module$require(null:68)
    at jdk.nashorn.internal.scripts.Script$Recompilation$289$57AAAAA$^eval_#88!17^eval_.L:1(/usr/local/lib/node_modules/falcor/node_modules/falcor-path-utils/lib/index.js:4)

**Comment by ramukima** [comment]
This is the workaround I am using...

```
bash-3.2$ cat lib/toTreeWithUnion.js 
/**
 * @param {Array} paths -
 * @returns {Object} -
 */
module.exports = function toTree(paths) {
    return function() {};
};
```

**Comment by lrowe** [comment]
@michaelbpaulson can we just delete the empty file here `lib/toTreeWithUnion.js`?

**Comment by ThePrimeagen** [comment]
I believe in you @lrowe
![do it](https://cloud.githubusercontent.com/assets/4458174/18454347/942de950-78f8-11e6-85c1-3624fd1f835b.gif)

The caption is a bit weird but I believe he is saying "Do It". ;)
